### ISSUE TITLE
Logout notification support

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/BFF#1]
* ping endpoint for JS to replace check_session (that won't slide cookie?)
* or signalr callback w/ JS library to get notified of backchannel logouts

**Comment by brockallen** [comment]
For the record, we have a polling capability for now to ~/bff/user with a ?slide=false option to prevent sliding of the session.

**Comment by ylr-research** [comment]
This is interesting. I can contribute here if you want to.

**Comment by damianh** [comment]
A push mechanism has some interesting challenges from a scale out perspective needing backplanes etc.

**Comment by LilitHakobyan** [comment]
Are there any plans to add a session cookie for BFF similar to idsrv.session to be able to detect the logout on a client app without calling bff/user?

**Comment by brockallen** [comment]
> Are there any plans to add a session cookie for BFF similar to idsrv.session to be able to detect the logout on a client app without calling bff/user?

Sorry -- I think your comment slipped thru the cracks. This is an excellent idea. We can think about if and how this might work for a 2.1 milestone. Thanks!

**Comment by brockallen** [comment]
> Are there any plans to add a session cookie for BFF similar to idsrv.session to be able to detect the logout on a client app without calling bff/user?

Question for you on this issue -- is your BFF client using front-channel or back-channel logout notification from your OIDC provider?

**Comment by brockallen** [comment]
> Are there any plans to add a session cookie for BFF similar to idsrv.session to be able to detect the logout on a client app without calling bff/user?

Just to follow up here, after more thinking... if the only logout notification to the client is back-channel, then this type of detection mechanism would not work. You need some request from the browser to the backend of the client app (the BFF) so that the server can update/remove/whatever this new session-like cookie would be. So I think the current polling to ~/bff/user?slide=false is the best approach for now if your client uses back-channel logout notifications. The only improvement here would be a push notification, but that would involve JS code, which is currently beyond the scope of the BFF library.

The suggestion you made would work great if the client uses front-channel logout notifications, though. The front-channel logout notification from the browser to the client allows the BFF to emit a response into the browser which could update/remove/whatever this new session-like cookie. Then of the SPA were open in another tab it could do the polling to check the cookie state (again, whatever those details may be). 

If your client app does not use either of these, then you'd be on your own to detect the session being terminated. It's possible you could use the check session endpoint, but that only works in same-site situations, and is again mainly JS you'd have to write. We could consider a sample for this, but it would not be JS that is somehow emitted (and supported) from this BFF library (due to the aforementioned scope constraints).

**Comment by ylr-research** [comment]
@brockallen Just to add more context to back-channel logout notification. BFF can include a background process to check the expiry of the session-like cookie, and if expired push a notification using SignalR. No JS involved. I'm willing to add that behavior if you like.

**Comment by LilitHakobyan** [comment]
@brockallen I got your suggestions. there was a problem also which multiple tabs, so when in one tab the user performs a logout the other tab stays active until the pooling mechanize will work ( in my case it working in each following minute ) i solve the issue using React Broadcast Channel API basically sending notification from the logout tab to another tab. Also, i have a session extending mechanism based on user activity and using the same API synchronized sessions between tabs.
But the case when the session cookies can be deleted directly from the browser is not solved the application will work until the pooling mechanism will be executed.

**Comment by brockallen** [comment]
Hi @ylr-research --

> Just to add more context to back-channel logout notification. BFF can include a background process to check the expiry of the session-like cookie, and if expired push a notification using SignalR. No JS involved. I'm willing to add that behavior if you like.

Can you elaborate on this, please?

**Comment by brockallen** [comment]
I think our plan is to provide samples for two of these:
https://github.com/DuendeSoftware/Samples/issues/108
https://github.com/DuendeSoftware/Samples/issues/109

**Comment by ylr-research** [comment]
I can have a [BackgroundService](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-7.0&tabs=visual-studio) for validating the cookie and if expired to push a notification with SignalR

**Comment by ylr-research** [comment]
Like this [example](https://github.com/ylr-research/BackgroundProgressNotifications). I will need to modify some stuff, but you get the idea. If it works, let me know.

**Comment by brockallen** [comment]
@dotnetspark sorry to pick this up so long from the last time (we were working on the IdentityServer release).

Anyway, back to your sample -- so in short, this is a polling approach on the server, right? There's code to check the server-side session, and when it's expired, the SignalR connection pings the client side code?

**Comment by dotnetspark** [comment]
No worries @brockallen. Yes! That's exactly the proposal. Does it work?

**Comment by brockallen** [comment]
> Does it work?

It's one way to go about it and I don't see anything wrong with it (but I've not spent any real time thinking about it).

We'd only be able to provide docs with this as a suggestion (and maybe a sample). We'd not be able to implement this as part of our implementation because we'd not want the dependency on SignalR from our library.

**Comment by brockallen** [comment]
And the more I think about it, this as a sample might get pretty involved pretty quick. How would you do this polling and then lookup of connection in a performant way? I'm guessing there's a bunch of state to maintain, and that's quickly becoming a new product in and of itself :)

**Comment by brockallen** [comment]
We have an open issue here https://github.com/DuendeSoftware/Samples/issues/108 to track working on this sample. Beyond that, I think everything in this issue has been addressed, so I'll close it unless there are other thoughts/comments, or I have missed something.

**Comment by dotnetspark** [comment]
Makes sense. Thanks!
