### ISSUE TITLE
Util.IsLocalUrl should not allow "~/"

### ISSUE THREAD

**Issue by ArturDorochowicz** [DuendeSoftware/BFF#117]
The code in `Util.IsLocalUrl` is clearly borrowed from MVC. The thing is that various parts of MVC recognize and resolve "\~/" in url strings. But in BFF the values that pass this are used in `AuthenticationProperties.RedirectUri` and the ultimate consumer of this is the OIDC authentication middleware which has no special processing for "~/".

I think the following fragment should be removed and return false.

https://github.com/DuendeSoftware/BFF/blob/17a3fc19678fed44c39861e3acefefda002d03c2/src/Duende.Bff/Endpoints/Util.cs#L28-L44

**Comment by brockallen** [comment]
Ok yea -- we don't do any special processing for ~/ so agreed, we should remove it.
