### ISSUE TITLE
Consider easier customization of returnUrl validation

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/BFF#126]
Right now the login and logout endpoint require an application local returnUrl.

There are scenarios where BFF and UI are separate - the only way right now to accomplish this is to replace the whole service - maybe a `IReturnUrlValidator` would make sense?

**Comment by brockallen** [comment]
Not sure if we need/want separate APIs for login vs logout, or just a single/simple method (as the PR does).

**Comment by JeremyVm** [comment]
Hi,

I have the following setup:

1 Blazor WASM app that is standalone: port 5000
1 YARP-BFF app: port 6000
1 IdentityServer app: port 7000

When I click on Login on the Blazor App I'm redirected to YARP-BFF app which redirects me to IdentityServer app.
Upon login I get redirected to the YARP-BFF app, but I get an error there that the page does not exist. I suspect the issue I'm having is what you're describing in your comment?

Based upon the description of your issue I would assume that I have replace the whole service. Can you @leastprivilege  specify in more detail which service I would have to replace?
