### ISSUE TITLE
More extensibility friendly DefaultHttpMessageInvokerFactory

### ISSUE THREAD

**Issue by ArturDorochowicz** [DuendeSoftware/BFF#136]
I'd like to suggest extracting the handler creation here to a separate virtual method:
https://github.com/DuendeSoftware/BFF/blob/0ad3cded9acceb2bab565bf110b2df73b5fc3fab/src/Duende.Bff.Yarp/DefaultHttpMessageInvokerFactory.cs#L26-L32

Something like:
```csharp
protected virtual HttpMessageHandler CreateHandler(string localPath)
{
   return new SocketsHttpHandler { /* ... */ };
}
```

This will allow derived classes to wrap the base handler in additional `DelegatingHandler`(s). For instance:
```csharp
protected override HttpMessageHandler CreateHandler(string localPath) 
{
   var handler = base.CreateHandler(localPath);
   var wrapper = new MyDelegatingHandler { InnerHandler = handler };
   return wrapper;
}
```

Currently if we just want to wrap the handler, we have to copy the code creating the `SocketsHttpHandler` from `DefaultHttpMessageInvokerFactory.CreateClient`.

**Comment by leastprivilege** [comment]
Sounds reasonable, do you want to propose a PR?
