### ISSUE TITLE
Add a ticket cleanup service

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/BFF#17]
For abandoned/expired tickets

Some starting code commented out in AuthenticationTicketExtensions.cs

**Comment by seges-tmc** [comment]
Any time frame on implementing this feature in BFF?

**Comment by brockallen** [comment]
Yes, this is something that we can get into the next release. I'm not sure when that will be yet, tho.

**Comment by brockallen** [comment]
@seges-tmc I submitted a PR. Any feedback is welcome.
