### ISSUE TITLE
Update for .NET 6's OnCheckSlidingExpiration

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/BFF#18]
Use the new OnCheckSlidingExpiration event to support the "noslide" feature on the ~/bff/user endpoint.

https://github.com/dotnet/aspnetcore/pull/33016

https://github.com/dotnet/aspnetcore/pull/33016/files#diff-889767564299ee0718b1e4bdf881cb7a684e8cdae7e68be270241e6e53702b37R21

**Comment by leastprivilege** [comment]
available in .NET 6 Preview 6

**Comment by leastprivilege** [comment]
done for 1.1
