### ISSUE TITLE
Consider defaulting to bearer token type when token type is missing

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/BFF#182]
There have been several support cases where the lack of a token type in unusual circumstances caused issues. When the token type is missing, we could assume that we should use the bearer token type as a fallback.

**Comment by josephdecock** [comment]
See https://github.com/DuendeSoftware/Support/issues/826, https://github.com/DuendeSoftware/Support/issues/829

**Comment by Vossekop** [comment]
Any idea when v2.1.2 will be released. We are hitting this issue and so we are stuck on 2.0.0 at the moment.

**Comment by josephdecock** [comment]
We're working on a release that will also add support for .NET 8, and hoping to release this week or early next.
