### ISSUE TITLE
Issue with EFCore session store implementation when using multiple DBContext

### ISSUE THREAD

**Issue by rahul7720** [DuendeSoftware/BFF#23]
Duende IdentityServer V5
Donnet 6 Preview 4

Below code is added to the StartUp class for EFCore based session store implementation.

```
services.AddBff()
    .AddEntityFrameworkServerSideSessions(options=> 
    {
        options.UseSqlServer(cn);        
    });
```

When the user tries to log in below exception is thrown: 

`InvalidOperationException: The DbContextOptions passed to the SessionDbContext constructor must be a DbContextOptions<SessionDbContext>. When registering multiple DbContext types, make sure that the constructor for each context type has a DbContextOptions<TContext> parameter rather than a non-generic DbContextOptions parameter.`

Note:
Another DbContext (`ApplicationDbContext`) also registered in the same class.

Possible solution:
Changing `SessionDbContext `the parameter to a generic parameter.

```
       public SessionDbContext(DbContextOptions<SessionDbContext> options) : base(options)
        {
        }
```

**Comment by leastprivilege** [comment]
Thanks! We will look into it.

**Comment by brockallen** [comment]
Merged, thanks
