### ISSUE TITLE
Question: Does this work for mobile apps and how should it be configured?

### ISSUE THREAD

**Issue by lnaie** [DuendeSoftware/BFF#26]
BFF for SPA scenario is more or less clear. Thanks for that.
How about the mobile apps (web based, native or xamarin)? Is it applicable and how?

Thanks,
Lucian

**Comment by leastprivilege** [comment]
It's not applicable. The whole premise of the BFF framework is to make browser-based applications more secure.

In mobile apps you have the luxury of not running in the browser.

**Comment by leastprivilege** [comment]
Maybe this is what you are looking for?

https://github.com/IdentityModel/IdentityModel.OidcClient
