### ISSUE TITLE
Claims not mapped when using cookies

### ISSUE THREAD

**Issue by murugaratham** [DuendeSoftware/BFF#29]
**Which version of Duende IdentityServer are you using?**
5.2.1
**Which version of .NET are you using?**
.net 5
**Describe the bug**
Identity Server + BFF + Cookies + AspNetIdentity results in 
```
[18:05:08 Information] Microsoft.AspNetCore.Authorization.DefaultAuthorizationService
Authorization failed. These requirements were not met:
ClaimsAuthorizationRequirement:Claim.Type=scope and Claim.Value is one of the following values: (myapi)
```

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**
To authorize users with correct scope

**Log output/exception with stacktrace**

```
data
```

**Additional context**

in startup.cs

```
.AddOpenIdConnect("oidc", options =>
            {
...
                options.Scope.Clear();
                options.Scope.Add("openid");
                options.Scope.Add("profile");
                options.Scope.Add("myapi");
                options.Scope.Add("offline_access");
```

```
 services.AddAuthorization(options =>
            {
                options.AddPolicy("MyApiScope", policy =>
                {
                    policy.RequireClaim("scope", "myapi");
                    ...
               }
        }
...
endpoints.MapControllers().RequireAuthorization("MyApiScope").AsBffApiEndpoint();
```

id server logs:

```

[18:05:07 Debug] Duende.IdentityServer.Validation.TokenValidator
Token validation success
{"ClientId": null, "ClientName": null, "ValidateLifetime": true, "AccessTokenType": "Jwt", "ExpectedScope": "openid", "TokenHandle": null, "JwtId": "C1B9ED46ACD5E6472DAD50CAF1E91D36", "Claims": {"iss": "https://localhost:5001", "nbf": 1625825107, "iat": 1625825107, "exp": 1625828707, "aud": "https://localhost:5001/resources", "scope": ["openid", "profile", "myapi", "offline_access"], "amr": "pwd", "client_id": "test", "sub": "89fcb5a9-2cdb-490b-838c-37290534a7be", "auth_time": 1625825106, "idp": "local", "sid": "B827C8AA731BA325A5054A486235D455", "jti": "C1B9ED46ACD5E6472DAD50CAF1E91D36"}, "$type": "TokenValidationLog"}

[18:05:07 Debug] Duende.IdentityServer.ResponseHandling.UserInfoResponseGenerator
Creating userinfo response

[18:05:07 Debug] Duende.IdentityServer.ResponseHandling.UserInfoResponseGenerator
Scopes in access token: openid profile myapi offline_access

[18:05:07 Debug] Duende.IdentityServer.EntityFramework.Stores.ResourceStore
Found ["profile", "openid"] identity scopes in database

[18:05:07 Debug] Duende.IdentityServer.ResponseHandling.UserInfoResponseGenerator
Requested claim types: profile preferred_username nickname middle_name given_name family_name name picture website gender birthdate zoneinfo locale updated_at sub

[18:05:07 Information] Duende.IdentityServer.ResponseHandling.UserInfoResponseGenerator
Profile service returned the following claim types: sub name given_name family_name website preferred_username

[18:05:07 Debug] Duende.IdentityServer.Endpoints.UserInfoEndpoint
End userinfo request


```

**Comment by leastprivilege** [comment]
Just so I understand - are you trying to control access to a BFF local API via a scope? Why? By definition, only valid users of the BFF have access to the BFF-local APIs.

**Comment by murugaratham** [comment]
Yup, I’m using Finbuckle.MultiTenant, the BFF is going to front a multitenanted api, which will have its own scope

**Comment by leastprivilege** [comment]
> the BFF is going to front a multitenanted api,

and is that a local API - or a remote API?

https://docs.duendesoftware.com/identityserver/v5/bff/apis/

**Comment by murugaratham** [comment]
It’s a Local Api

SPA -> BFF MultiTenant API -> Identity Server 
  |
  v
Identity Server (same instance of identity server)

**Comment by leastprivilege** [comment]
if it is a local API - then by definition only the local front-end can access it. No scopes required.

**Comment by murugaratham** [comment]
Hmm, i have different users that might have different scopes, for example, user A has admin scope n is allowed to invoke admin level API, but normal user have typical access, I still believe this is a legit use case?

**Comment by murugaratham** [comment]
I might be confused, but in JWT, identity server is issuing “custom api claim” but the cookies apparently you are explaining, only derived id_token and claims?

**Comment by leastprivilege** [comment]
If you are calling a local API - there is no OAuth in use - thus no access token. Access tokens are only needed when calling remote APIs.

That being said, you are in full control of the session and claims that get sent to local APIs.

https://docs.duendesoftware.com/identityserver/v5/bff/session/management/#user

But for your use case, this is not needed.

**Comment by murugaratham** [comment]
So for SPA on nginx, making a default api call hosted on API (enriched by BFF and protected using Authorization attribute) and using cookies don’t use open id connect? Just double checking, coz from the documentation, it’s that BFF is transforming/safely handling oauth, so that SPA can just use cookies and still get oauth managed

**Comment by leastprivilege** [comment]
Authentication is done by OpenID Connect (not OAuth) - the resulting id_token is transformed into the session (you can customize this). The session is represented by the cookie flowing between the browser front-end and the BFF.

The session claims is what local APIs will "see" as the caller.

To re-iterate: since by definition only valid users of the application have access to local APIs, scopes are not needed.

I know this might be confusing, and there are multiple layers of abstractions involved.

**Comment by murugaratham** [comment]
here's what i get from 
```
bff/user

[
  {
    "type": "http://schemas.microsoft.com/claims/authnmethodsreferences",
    "value": "pwd"
  },
  {
    "type": "sid",
    "value": "B827C8AA731BA325A5054A486235D455"
  },
  {
    "type": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
    "value": "89fcb5a9-2cdb-490b-838c-37290534a7be"
  },
  {
    "type": "auth_time",
    "value": "1625825106"
  },
  {
    "type": "http://schemas.microsoft.com/identity/claims/identityprovider",
    "value": "local"
  },
  {
    "type": "name",
    "value": "Charlie Brown"
  },
  {
    "type": "given_name",
    "value": "Charlie"
  },
  {
    "type": "family_name",
    "value": "Brown"
  },
  {
    "type": "bff:logout_url",
    "value": "/bff/logout?sid=B827C8AA731BA325A5054A486235D455"
  },
  {
    "type": "bff:session_expires_in",
    "value": 17900
  },
  {
    "type": "bff:session_state",
    "value": "snn07HPjSrm7u8n0_kArGtYV8X1ZHmwl3LfA5jBf4T0.13D01C3DC456213710BC786FD81AF33E"
  }
]
```

So SPA (standalone nginx) -> API + BFF AdminController with [Authorize("MyApi")] using cookies should not be done?
I am planning for some Apis that would require additional claim (managed by aspnet identity when users are created)

From Identity Server

```
{
  "ClientId": null,
  "ClientName": null,
  "ValidateLifetime": true,
  "AccessTokenType": "Jwt",
  "ExpectedScope": "openid",
  "TokenHandle": null,
  "JwtId": "C1B9ED46ACD5E6472DAD50CAF1E91D36",
  "Claims": {
    "iss": "https://localhost:5001",
    "nbf": 1625825107,
    "iat": 1625825107,
    "exp": 1625828707,
    "aud": "https://localhost:5001/resources",
    "scope": [
      "openid",
      "profile",
      "myapi", //<-- **it's within JWT here**
      "offline_access"
    ],
    "amr": "pwd",
    "client_id": "test",
    "sub": "89fcb5a9-2cdb-490b-838c-37290534a7be",
    "auth_time": 1625825106,
    "idp": "local",
    "sid": "B827C8AA731BA325A5054A486235D455",
    "jti": "C1B9ED46ACD5E6472DAD50CAF1E91D36"
  },
  "$type": "TokenValidationLog"
}
```

How should i add such scope "myapi" and restrict access to certain api?

**Comment by leastprivilege** [comment]
Not sure what to say - I think I already gave you all the answers.

Maybe you would benefit from our consulting offering to understand the architecture from the ground up.
