### ISSUE TITLE
__Host- cookie prefix breaks on Chrome when hosting in an IIS subdirectory.

### ISSUE THREAD

**Issue by VictorioBerra** [DuendeSoftware/BFF#33]
https://github.com/DuendeSoftware/BFF/blob/2cfddbc6327f841b24a43d28f14fc15937371741/samples/Host5/Startup.cs#L51

When hosting on IIS as an application under a website (www.mydomain.com/myapp1) the cookie will have a Domain value of /myapp1

This violates draft-west-cookie-prefixes-05, and the cookie is rejected under chrome (Version 92.0.4515.107 (Official Build) (64-bit))

**Comment by brockallen** [comment]
Is the path being set? That's not allowed, I guess:

https://www.chromestatus.com/feature/4952188392570880

**Comment by brockallen** [comment]
And once you changed it to Path="/" it's working?

**Comment by VictorioBerra** [comment]
Correct, without setting `options.Cookie.Path = "/"` the Chrome cookie explorer will show the cookie was denied and it explains the cookie prefix error.

After setting the above variable and redeploying, the cookie was successfully set.
