### ISSUE TITLE
BFF Blazor - login and remember me

### ISSUE THREAD

**Issue by kjdamen** [DuendeSoftware/BFF#36]
Version:
Duende IdentityServer 5.2.2 
Identity server project on .NET 6.0 with Entity Framework and ASP.NET Identity (with 2 factor authentication).

BBF Blazor sample:
When you choose the option 'Remember me' while logging in, you will be redirected back to the client and the claims will be shown. However, when you restart the application again, the login button will appear again.

In the browser console you will see the following result when starting the application:
	Sending HTTP request GET https://localhost:5002/bff/user
	Failed to load resource: the server responded with a status of 401 ()

After you click on login again, the following error message appears:
	SqlException: Cannot insert duplicate key row in object 'dbo.UserSessions' with unique index 'IX_UserSessions_ApplicationName_SessionId'. 
	The duplicate key value is (Blazor.Server, BC12C0A9300B154697BF1F184E34AC0E).

When you now empty the UserSessions table and restart the application, you will still see the login button, but after you have clicked on it, you will immediately see your claims without logging in again.

In the identity server account options the AllowRememberLogin property is set to true.

Expected result:
When you choose the option 'Remember me' during login and you restart the application, the user would be immediately retrieved and the claims displayed.

**Comment by leastprivilege** [comment]
This is expected behavior and applies to all web applications using SSO.

The freshly started Blazor app (or any app really) cannot know if the user is already authenticated with the authentication system. It must do a roundtrip first to join the existing session.

wrt the Exception - we will have a look @brockallen

**Comment by leastprivilege** [comment]
@brockallen could you have a look at above exception?

**Comment by brockallen** [comment]
Sorry that this slipped thru the cracks. I thought this issue sounded familiar: https://github.com/DuendeSoftware/BFF/commit/39669be45664dd487884d982f3b615f1ba3b4f35

I fixed this in August already, but I guess we've not had a release since the commit.

**Comment by leastprivilege** [comment]
OK - will do a new release with the changes discussed today ASAP.

**Comment by leastprivilege** [comment]
Update pushed
