### ISSUE TITLE
Antiforgery token validation failed

### ISSUE THREAD

**Issue by ylr-research** [DuendeSoftware/BFF#46]
I have a Blazor app and for some reason there are 2 endpoinst failing with a 401 and when I checked the event logs I see this.

Category: Duende.Bff.Endpoints.BffMiddleware
EventId: 2
SpanId: 6d3fc7c7594838cc
TraceId: b9e4542533b256b89b48a98ea9fad13e
ParentId: 0000000000000000
RequestId: 80000020-0002-c800-b63f-84710c7967bb
RequestPath: /myapipath/

Anti-forgery validation failed. local path: '/myapipath/'

In `Startup.cs` I have this
```
                services.AddAuthentication(options =>
                {
                     //hidden for brevity
                })
                .AddCookie(openIdSettings.OpenIdBrowserUXDefaultScheme, options =>
                {
                    options.Cookie.Name = "__Host_Blazor";
                    options.Cookie.SameSite = SameSiteMode.Strict;
                })
                .AddOpenIdConnect(openIdSettings.OpenIdBrowserUXDefaultChallengeScheme, options =>
                {
                     //hidden for brevity
                });
```

Any suggestion as to how this can be fixed?

Thanks beforehand.

**Comment by brockallen** [comment]
Are you adding the anti-forgery token header to each API call?

https://docs.duendesoftware.com/identityserver/v5/bff/apis/local/

**Comment by ylr-research** [comment]
Yes, I do.

## Program.cs
```
            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            builder.Services.AddTransient<AntiforgeryHandler>();

            builder.Services.AddHttpClient("backend", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)).AddHttpMessageHandler<AntiforgeryHandler>();
            builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("backend"));
```

## AntiforgeryHandler
```
    public class AntiforgeryHandler : DelegatingHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            request.Headers.Add("X-CSRF", "1");
            return base.SendAsync(request, cancellationToken);
        }
    }
```

**Comment by ylr-research** [comment]
I think I know what could be. When using NavigationManager or HttpClient everything is fine. This error only happens with JSInterop calls which leads me to believe the JS function performing a request is missing the "X-CSRF" header

**Comment by ylr-research** [comment]
BTW, the JS function is sending a GET. Does a GET has to have AntiforgeryToken or is there a way to ignore it?

**Comment by brockallen** [comment]
Yes, all Ajax calls should include the anti-forgery headers. It can be disabled, but it's suggested that you don't do that :)

**Comment by ylr-research** [comment]
it's not even an ajax call but a location change initiated by the browser. Do you see any way I can add the cookie created by the `AntiforgeryHandler`?

`    window.location.href = url;`

**Comment by brockallen** [comment]
For regular redirects (GET from the window, as opposed to Ajax calls) we don't add any anti-forgery (except for logout). Did you add "AsBffEndpoint()" to those non-Ajax endpoints in the route table? If so, that might explain it.

**Comment by ylr-research** [comment]
I see. I have it like that for all endpoints which explains why. I will have to exclude that specific one

**Comment by brockallen** [comment]
AddControllers is for API endpoints. AddControllersWithViews is for UI endpoints. Just use AsBffEndpoint on the API endpoints. 

Unless I'm missing something?

**Comment by ylr-research** [comment]
In this case one endpoint opens a PDF file and while the other endpoint downloads a .zip file

**Comment by brockallen** [comment]
Then for those endpoints don't mark them as `AsBffEndpoint`.

**Comment by ylr-research** [comment]
sure let me try that

**Comment by ylr-research** [comment]
This is what I have Brock.

```
                    endpoints.MapBffManagementEndpoints();
                    endpoints.MapRemoteBffApiEndpoint("/api", https://localhost:5010).RequireAccessToken(TokenType.UserOrClient);
                    endpoints.MapControllers().RequireAuthorization().AsBffApiEndpoint();
```

Is there any way I can exclude those API?

**Comment by leastprivilege** [comment]
I think you can use the `[BffApi]` attribute on the specific API action method and disable anti-forgery.

**Comment by ylr-research** [comment]
Let me try this

**Comment by ylr-research** [comment]
All good. Thanks
