### ISSUE TITLE
Read value of cookie __Host_Blazor

### ISSUE THREAD

**Issue by ylr-research** [DuendeSoftware/BFF#48]
This is more a question than a bug.

I need to read the value of the cookie, but for some reason it keeps returning the same hashed value.

`var cookiePlainText = HttpUtility.UrlDecode(context.Request.Cookies["__Host_Blazor"]);`

Is there any way I can get the plain text for that cookie?

**Comment by brockallen** [comment]
What are you trying to do by reading the cookie? It's issued by the cookie authentication handler and is data protected.

**Comment by ylr-research** [comment]
Brock, I'm trying to implement a session timeout, for that I need to check the cookie last time used. Do you have any suggestion as to how to do so?

**Comment by brockallen** [comment]
Yes -- use HttpContext.AuthenticateAsync -- that's the abstraction for getting to that data.

**Comment by ylr-research** [comment]
Got it. thanks
