### ISSUE TITLE
401 when token expired and Reason comes blank

### ISSUE THREAD

**Issue by ylr-research** [DuendeSoftware/BFF#49]
Hi Brock,

In my Blazor Server project in `Startup.cs` I set the cookie to expire after 4 min. Once passed that time, I interact with a component that needs to talk to the server and I see nothing is happening. After opening the dev tools I realize there is a 401 result. I added a breakpoint in the component to see the reason for the 401 hoping it'll say something like token expired or so. To my surprise the Reason property is empty. Most importantly, if the token is expired shouldn't bff middleware sent me back to bff/login or do I have to manually set that?

Thanks in advance

**Comment by brockallen** [comment]
I'm not 100% clear on where the failure is occurring in your your layers. But if the 401 is being returned to your client-side JS, then it means you need to log the user in again. And the ASP.NET plumbing doesn't return you a reason.

**Comment by ylr-research** [comment]
thanks for the quick response. In that case -I know this is outside the scope of BFF- there is no difference between a user not having access to a resource than a token expired. But going back to my main issue, once expired is there any setting or something else do you know of, I can use to send the user to bff/login? Otherwise, I will need to add that logic in every component using `HttpClient`.

**Comment by brockallen** [comment]
403 is the correct status code when the user is not allowed due to authorization logic.

**Comment by ylr-research** [comment]
I added the following, but seems not to be working -the redirection-. If I add this `app.Use` below `UseAuthorization()`, when token expired, it will return 401 without executing `app.Use`.

```
                app.Use(async (context, next) =>
                {
                    var authResult = await context.AuthenticateAsync();
                    if (authResult.Failure.Message == "Ticket expired")
                    {
                        context.Response.Redirect("https://localhost:44382/bff/login");
                    }

                    await next();
                });
                app.UseAuthentication();
                app.UseBff();
                app.UseAuthorization();
```

**Comment by ylr-research** [comment]
@brockallen is there any way to redirect to bff/login is 401 is received?

**Comment by brockallen** [comment]
That will not work. You are making an AJAX call expecting JSON, and it instead redirects to a login page, which will return HTML to your JS. You need to have some interception layer in your JS to check for 401 then redirect the window to the login page.

**Comment by ylr-research** [comment]
This can be closed
