### ISSUE TITLE
PathBase is ignored in bff:logout_url returned from /bff/user endpoint

### ISSUE THREAD

**Issue by dgrozenok** [DuendeSoftware/BFF#53]
**Which version of Duende IdentityServer are you using?**
- Duende.IdentityServer: 5.2.3
- Duende.BFF: 1.0.0

**Which version of .NET are you using?**
- 6.0

**Describe the bug**
BFF-based ASP.NET Core WebApi application with `UsePathBase` set responds to the user endpoint with the `bff:logout_url` property ignoring the PathBase.

**To Reproduce**

- Create project from the "Duende BFF with JavaScript" template.
- In `Startup.cs` modify `Startup.Configure` method by adding as the first statement

```csharp
app.UsePathBase("/api");
```

- Run application, login and request `/api/bff/user`
- Look at the response's array element with `type=bff:logout_url`
- The result is

```json
{
  "type": "bff:logout_url",
  "value": "/bff/logout?sid=E18EF260B13B4E494C0CE1D449EFAFCC"
},
```

**Expected behavior**

```json
{
  "type": "bff:logout_url",
  "value": "/api/bff/logout?sid=E18EF260B13B4E494C0CE1D449EFAFCC"
},
```

**Additional context**

In production environment the BFF server is running behind a reverse proxy, so the PathBase is setup to properly route the requests from the SPA application to the BFF server. The logout URL is though returned without the PathBase and could not be properly routed. For example, here is the proxy configuration for dev server setup using http-proxy-middleware:
```JavaScript
  app.use(
    '/api',
    createProxyMiddleware({
      target: 'https://localhost:5001',
      secure: false,
      headers: {"Connection": "keep-alive"}
    })
  );
```

**Comment by leastprivilege** [comment]
thanks! We will have a look.

**Comment by leastprivilege** [comment]
Will update for the 1.1 release. thanks!

**Comment by leastprivilege** [comment]
The fix is merged into main - will publish soon.

**Comment by dgrozenok** [comment]
Great! Thank you so much!

**Comment by leastprivilege** [comment]
Released
