### ISSUE TITLE
Feature Request: Option to maintain claim type names for standard claim types on bff user endpoint

### ISSUE THREAD

**Issue by ace90210** [DuendeSoftware/BFF#54]
### The issue
We are implementing BFF into a large existing project and want to minimize the changes to our clients. Currently we have a number of claims returned such as "given_name", "email" and others. When implementing the BFF solution the user endpoint is changing the claim types of some of claims to types like "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname". This creates an additional breaking change our consuming clients need to address. Ideally we want to not change anything about the data they are used to mapping, especially as its not clear what triggers some claims to be renamed and what they are renamed too (for example strangling we have a "subjectId" claim that gets changed to "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier" which doesn't seem the most obvious match.

### Current workaround
The current workaround i have implemented (as i am not aware of a better solution at the moment) is a custom claims transformer to replace the claims with the original type names but this seems sub optimal and requires knowing in advance what claims need transforming.

### Possible solution
Ideally a BFF option to disable the claim types being changed would be best so it can transparently just pass through the claims as they were received. If not an easier with to map claims without implementing a custom transformer would be helpful.

**Comment by brockallen** [comment]
I suspect the issue is the OIDC handler is renaming your claims:

https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by ace90210** [comment]
Thanks for the prompt response, it does seem to be exactly that. I just could not find a way to force it to not rename them and the built in methods only stop name and role but many others are being renamed so i had hoping i was missing something. If this is outside your control and out of scope to add a custom workaround to BFF i understand. 

The current workaround i have is working and will resolve this issue for now but has the downside of needing to know in advance what claims are going to be renamed.

**Comment by brockallen** [comment]
On the OIDC options, there's a MapInboundClaims that you can set to false.

**Comment by ace90210** [comment]
Thanks we are currently on .net core 3.1 (should upgrade to 6 in near future). that seems to be missing from the core 3.1 openidconnect package. It was added in 5.0.0 which depends on .net core 5.0 with no support for 3.1.

However i found another method of achieving the same result in 3.1

` options.SecurityTokenValidator = new JwtSecurityTokenHandler
                {
                    MapInboundClaims = false
                };`
                
                Thanks for your help.
