### ISSUE TITLE
Question: Blazor BFF with Additional API

### ISSUE THREAD

**Issue by LeeStevens318** [DuendeSoftware/BFF#68]
I'm using Blazor BFF from the samples repository witch already sets up the authentication for the "local" api on the server project. 

```
// HTTP client configuration
builder.Services.AddTransient<AntiforgeryHandler>();
builder.Services.AddHttpClient("backend", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)).AddHttpMessageHandler<AntiforgeryHandler>();
builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("backend"));
```

Is there a way to register another API passing the token? I.e:
```
builder.Services.AddScoped<UserService>();
builder.Services.AddHttpClient<UserService>("API", client => client.BaseAddress = new Uri(builder.Configuration["API"]!));
```

I'm aware of the `AddHttpMessageHandler` and could create my own Handler to add the `AuthenticationHeaderValue` but i'm wondering if there is already something inbuilt? 

PS. The API is protected by the same IdentityServer.

**Comment by leastprivilege** [comment]
This would mean the token would be available to the Blazor frontend and defeat the purpose of the BFF pattern.

You have two options

* call a local API endpoint on the backend that makes the server side remote API call with the token
* use a remote API endpoint / YARP for reverse proxying

both is described here:
https://docs.duendesoftware.com/identityserver/v6/bff/apis/remote/

**Comment by LeeStevens318** [comment]
Thank you, i went with the HTTP forwarder!
