### ISSUE TITLE
miss IdTokenHint in call endsession endpoint

### ISSUE THREAD

**Issue by nmr1367** [DuendeSoftware/BFF#69]
hi. this is my bug.
![bff](https://user-images.githubusercontent.com/27186434/152216477-8d6a7166-15a8-4300-89d3-58cbf51aa050.png)

**Comment by brockallen** [comment]
Can you explain, please -- the picture is not sufficient for me to understand what you're trying to show.

**Comment by nmr1367** [comment]
i cant speak english. this pic is my best.
my senario:
1. multi client
2. multi bff
3. backchannel
after logout first client other client cant complete logout.

**Comment by nmr1367** [comment]
1. after logout bff 1. identity server call backchannel endpoint in bff 2. remove user session
https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff/SessionManagement/SessionRevocationService.cs#L74
2. next request from bff 2. ServerSideTicketStore.RetrieveAsync pervent cookie authenticate
https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff/SessionManagement/ServerSideTicketStore.cs#L77
3. after trigger idp SignOut
https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff/Endpoints/DefaultLogoutService.cs#L74 
4. cant fill IdTokenHint by OpenIdConnectHandler
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L231
5. Identity Server before signout by bff1 and call endsession endpoint by bff 2 in Identity Server without IdTokenHint. 
6. cant return to PostLogoutRedirectUri

**Comment by brockallen** [comment]
> after logout first client other client cant complete logout

Ok, that's what I thought you were getting at (but I wanted to confirm). So my advice to you is that when your BFF2 gets back 401 because the user is not logged in anymore, do not send the user to ~/bff/logout. I don't think it makes sense to do that.

**Comment by nmr1367** [comment]
thx. ok, but i think ~/bff/logout can return 401 for not logged user.

**Comment by leastprivilege** [comment]
@brockallen let's come to a conclusion here for the next release

**Comment by brockallen** [comment]
Since the ~/bff/logout is a browser navigate endpoint, a 401 would not help anyway, so there's no change that we can make here. We will be making the default implementations virtual in case you need/want to override the base behaviors.
