### ISSUE TITLE
BFF Can't user local API and Remote API in the same project

### ISSUE THREAD

**Issue by riaadh** [DuendeSoftware/BFF#70]
Hello, 
I am using the BFF .net 6 React  sample here  https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/BFF/ReactBffSample/src/FrontendHost/Program.cs
Local API and Remote API each one works fine when enabled alone
But when i want to use both (same endpoint i want them to be redirected to my local controller, and other just a proxy to other api ) it dont work, all routes are redirected to local controller or not found error.

```
               // local APIs
                endpoints.MapControllers()
                    .RequireAuthorization()
                    .AsBffApiEndpoint();

                // login, logout, user, backchannel logout...
                endpoints.MapBffManagementEndpoints();
                
                // proxy endpoint for cross-site APIs
                // all calls to /api/* will be forwarded to the remote API
                // user or client access token will be attached in API call
                // user access token will be managed automatically using the refresh token
                endpoints.MapRemoteBffApiEndpoint("/api", "https://localhost:5010")
                    .RequireAccessToken(TokenType.UserOrClient);

```
thank you for your help.

**Comment by leastprivilege** [comment]
On the same local URL?

**Comment by riaadh** [comment]
No on twh different url

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by leastprivilege** [comment]
That should work. Do you have more details.

**Comment by leastprivilege** [comment]
any update?

**Comment by jawand** [comment]
@leastprivilege I have completely unrelated question. Sorry to jump in. My question might be naïve but here I go.

I host a react app on domain my.react.app and this app will call my bff hosted at my.bff.app

Now, Since both apps are on different domain. How, the login cookie will be shared with my.react.app ? Since both apps are on different domains.

**Comment by brockallen** [comment]
@jawand:

> @leastprivilege I have completely unrelated question. Sorry to jump in. My question might be naïve but here I go.

Please open a new discussion: https://github.com/DuendeSoftware/BFF/discussions

**Comment by brockallen** [comment]
Closing, as not more details were provided. If you have more info, please reopen.
