### ISSUE TITLE
Option to disable anti-forgery check when using reverse proxy

### ISSUE THREAD

**Issue by andrerav** [DuendeSoftware/BFF#81]
The anti-forgery check that is applied when using YARP makes testing and debugging API's during development somewhat cumbersome. A simple option to disable this would be very helpful. Something along the lines of:

```csharp
builder.Services.AddBff()
                .AddServerSideSessions();
                .AddReverseProxy()
                .AddTransforms<AccessTokenTransformProvider>()
                .WithAccessToken(...)
                .WithAntiforgeryCheck(false)
```

**Comment by andrerav** [comment]
It seems this could already be solved by replacing a call to `MapBffReverseProxy()` with a call to MapReverseProxy().AsBffApiEndpoint() and passing the appropriate argument to the `AsBffApiEndpoint()` extension method, as shown below:

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapBffManagementEndpoints();
    endpoints.MapReverseProxy()
             .AsBffApiEndpoint(false);
});
```

In that case, it would be nice if the `MapBffReverseProxy()` extension could accept a parameter that could be passed to `AsBffApiEndpoint()`.

**Comment by leastprivilege** [comment]
merged. thanks!
